# Generated by Django 5.0.6 on 2024-05-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=22, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='avatar/')),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'auth_users',
            },
        ),
    ]
